//
// Created by curti on 2019-02-06.
//

#ifndef BELLAMYCURTIS_ASSIGNMENT01_GOOGLEPAGERANK_HPP
#define BELLAMYCURTIS_ASSIGNMENT01_GOOGLEPAGERANK_HPP


class GooglePageRank {

};


#endif //BELLAMYCURTIS_ASSIGNMENT01_GOOGLEPAGERANK_HPP
